import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

export const ACTIVITY_START = "<!-- AUTO:ACTIVITY:START -->";
export const ACTIVITY_END = "<!-- AUTO:ACTIVITY:END -->";

function escapeCell(value) {
  return String(value).replaceAll("|", "\\|").replaceAll("\n", " ");
}

function badgeSegment(value) {
  return encodeURIComponent(String(value).replaceAll("-", "--").replaceAll("_", "__").replaceAll(" ", "_"));
}

function renderLinks(links) {
  return links.map((link) => {
    const logo = link.logo ? `&logo=${encodeURIComponent(link.logo)}&logoColor=white` : "";
    const image = `https://img.shields.io/badge/${badgeSegment(link.label)}-${badgeSegment(link.value)}-${link.color}?style=for-the-badge${logo}`;
    return `  <a href="${link.url}"><img alt="${link.label}" src="${image}"></a>`;
  }).join("\n");
}

function renderFocus(focus) {
  return [
    "| Area | What I am exploring |",
    "| --- | --- |",
    ...focus.map((item) => `| **${escapeCell(item.name)}** | ${escapeCell(item.description)} |`)
  ].join("\n");
}

function renderProjects(projects) {
  return [
    "| Project | Focus | Why it matters |",
    "| --- | --- | --- |",
    ...projects.map((project) => {
      const homepage = project.homepage ? ` [Live](${project.homepage})` : "";
      return `| [**${escapeCell(project.name)}**](${project.url}) | ${escapeCell(project.focus)} | ${escapeCell(project.summary)}${homepage} |`;
    })
  ].join("\n");
}

function extractActivity(readme) {
  const startIndex = readme.indexOf(ACTIVITY_START);
  const endIndex = readme.indexOf(ACTIVITY_END);
  if (startIndex === -1 || endIndex === -1 || endIndex <= startIndex) return null;
  return readme.slice(startIndex + ACTIVITY_START.length, endIndex).trim();
}

async function readExistingActivity(readmePath) {
  try {
    const existing = await readFile(readmePath, "utf8");
    return extractActivity(existing);
  } catch (error) {
    if (error.code === "ENOENT") return null;
    throw error;
  }
}

export async function generateProfileReadme({ config, manifest, readmePath }) {
  const existingActivity = await readExistingActivity(readmePath);
  const activity = existingActivity || "_Recent public activity will appear here after the workflow runs._";
  const activitySection = config.activity.enabled
    ? `\n## Recent Activity\n\n${ACTIVITY_START}\n${activity}\n${ACTIVITY_END}\n`
    : "";
  const techStack = config.techStack.map((item) => `\`${item}\``).join(" · ");
  const about = config.profile.about.join("\n\n");

  const readme = `<!-- Generated by GitHub Profile Agent Console. Edit profile.config.json, then run npm run generate. -->
<p align="center">
  <picture>
    <source media="(max-width: 760px) and (prefers-color-scheme: dark)" srcset="./assets/hero/${manifest.assets.mobileDark}">
    <source media="(max-width: 760px)" srcset="./assets/hero/${manifest.assets.mobileLight}">
    <source media="(prefers-color-scheme: dark)" srcset="./assets/hero/${manifest.assets.desktopDark}">
    <source media="(prefers-color-scheme: light)" srcset="./assets/hero/${manifest.assets.desktopLight}">
    <img src="./assets/hero/${manifest.assets.desktopDark}" alt="${config.profile.name} - ${config.profile.headline}" width="100%">
  </picture>
</p>

<p align="center">
${renderLinks(config.links)}
</p>

<div align="center">
  <img src="https://capsule-render.vercel.app/api?type=transparent&color=22D3EE&height=50&section=header&text=GitHub%20Analytics&fontSize=24&fontAlignY=40" />
</div>
<p align="center">
  <img width="48%" src="https://github-readme-stats.vercel.app/api?username=${config.profile.username}&show_icons=true&title_color=22D3EE&text_color=E5E7EB&icon_color=38BDF8&bg_color=07111F&hide_border=true&theme=transparent" />
  <img width="48%" src="https://github-readme-stats.vercel.app/api/top-langs/?username=${config.profile.username}&layout=compact&title_color=22D3EE&text_color=E5E7EB&bg_color=07111F&hide_border=true&theme=transparent" />
</p>
<p align="center">
  <img width="100%" src="https://github-readme-activity-graph.vercel.app/graph?username=${config.profile.username}&bg_color=07111F&color=22D3EE&line=38BDF8&point=E5E7EB&area=true&hide_border=true" />
</p>

<div align="center">
  <img src="https://capsule-render.vercel.app/api?type=transparent&color=22D3EE&height=50&section=header&text=Featured%20Projects&fontSize=24&fontAlignY=40" />
</div>
<p align="center">
  <a href="https://github.com/${config.profile.username}/Themis---Alt">
    <img width="48%" src="https://github-readme-stats.vercel.app/api/pin/?username=${config.profile.username}&repo=Themis---Alt&title_color=22D3EE&text_color=E5E7EB&icon_color=38BDF8&bg_color=07111F&hide_border=true&theme=transparent" />
  </a>
  <a href="https://github.com/${config.profile.username}/krypts">
    <img width="48%" src="https://github-readme-stats.vercel.app/api/pin/?username=${config.profile.username}&repo=krypts&title_color=22D3EE&text_color=E5E7EB&icon_color=38BDF8&bg_color=07111F&hide_border=true&theme=transparent" />
  </a>
</p>

<div align="center">
  <img src="https://capsule-render.vercel.app/api?type=transparent&color=22D3EE&height=50&section=header&text=Tech%20Stack&fontSize=24&fontAlignY=40" />
</div>
<p align="center">
  <code>Python</code> <code>PyTorch</code> <code>TensorFlow</code> <code>Scikit-learn</code> <code>TypeScript</code> <code>Next.js</code>
</p>

${activitySection}
---

<p align="center">
  ${config.footer}
</p>
`;

  await writeFile(resolve(readmePath), readme);
  return readme;
}
